# Generated by Django 2.2.10 on 2020-03-09 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petdocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Пол')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='PetStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Статус питомца')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Вид животного')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Кличка')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('photo', models.ImageField(blank=True, upload_to='img', verbose_name='Фото')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Breed', verbose_name='Порода')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_registration', to='petdocs.Registration', verbose_name='Регистрационный документ')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Gender', verbose_name='Пол')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petdocs.Owner', verbose_name='Владелец')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Species', verbose_name='Вид животного')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.PetStatus', verbose_name='Статус питомца')),
            ],
        ),
    ]
