# Generated by Django 2.2.10 on 2020-03-07 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Фото'),
        ),
    ]
