# Generated by Django 3.0.1 on 2020-02-18 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20191222_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Вид животного')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Species', verbose_name='Вид животного'),
            preserve_default=False,
        ),
    ]
