# Generated by Django 2.2.10 on 2020-02-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20200223_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
