# Generated by Django 2.2.10 on 2020-03-04 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20200229_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Gender', verbose_name='Порода'),
            preserve_default=False,
        ),
    ]
