# Generated by Django 2.2.10 on 2020-03-09 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=256, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('note', models.CharField(max_length=256, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='PetShelteringRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('phone_num', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес эл.почты')),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=20, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_num', models.CharField(auto_created=True, blank=True, max_length=256, null=True, verbose_name='Регистрационный номер')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата регистрации')),
                ('cage', models.CharField(max_length=10, verbose_name='Номер клетки')),
            ],
        ),
    ]
