# Generated by Django 2.2.10 on 2020-03-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('petdocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshelteringrequest',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_sheltering_request_pet', to='pets.Pet', verbose_name='Питомец'),
        ),
    ]
