# Generated by Django 2.2.10 on 2020-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdocs', '0002_petshelteringrequest_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshelteringrequest',
            name='email',
            field=models.EmailField(default='none@none.com', max_length=254, verbose_name='Адрес эл.почты'),
            preserve_default=False,
        ),
    ]
