# Generated by Django 3.0.1 on 2020-02-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petdocs', '0003_petshelteringrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshelteringrequest',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='Комментарии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petshelteringrequest',
            name='firstname',
            field=models.CharField(max_length=256, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petshelteringrequest',
            name='lastname',
            field=models.CharField(max_length=256, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petshelteringrequest',
            name='middlename',
            field=models.CharField(max_length=256, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petshelteringrequest',
            name='phone_num',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
