# Generated by Django 2.2.10 on 2020-02-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20200229_1739'),
        ('petdocs', '0004_auto_20200223_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshelteringrequest',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_sheltering_request_pet', to='pets.Pet', verbose_name='Питомец'),
        ),
    ]
